depth = -1001
global.combo = 0
global.score = 0
global.combotimer = 0
global.combotimer_full = 300
global.secrets = 0
global.treasure = 0
combo_hot_x = 0
tvx = 1696
tvy = 160
tv2x = 256
tv2y = 192
tv2spr = noone
scr_random()
tv2spridle = irandom_range(30, 190)
tv2smg = 0
fakescore = 0
comboscoreplus = 0
csp_spd = 0
cbs_first = 0
hurttimer = 0
bigs_sound = sfx_enemyhit
escape_timer_scale = 4
escape_timer_scale_hold = 20
excape_timer_shk = 0
escape_timer_goaway = 0
global.stylin_score = 0
tvopac = 1
tv2opac = 1
timeropac = 1
cashopac = 1
tvyplus = 0
tv2yplus = 0
combometer_y = -450
combometer_vsp = 0
combometer_started = 0
shk_x = 0
shk_y = 0
shk_strength = 3
shk2_x = 0
shk2_y = 0
shk2_strength = 4
msg_txt = "NAN"
msg_time = 180
msg_y = 320
msg_xoff = 0
msg_xoff_cd = 0
rmname = "NAN"
rmname_time = 120
rmname_y = -320
rmg_txt = "Sample text"
rmg_x = -1000
rmg_active = 0
rmg_spr = spr_radiomessage_start
rmg_img = 0
rmg_bubble = 0
rmg2_spr = spr_tv_player2_talk
rmg2_img = 0
rmg_surface = -1
prevstate = "normal"
tvnoise = 4
current_comborank = 0
okasy_comborank = 0
okasy_combo = 0
comborank_scale = 2.4
fuelup = 0
tv_hurttime = 40
tv_scoreup = 200
tv_secretfound = 200
hm_img = 0
hm_spr = spr_microwave_heat1
hudrank_scale = 1
hudrank = "s"
funmet_y = 380
if (ds_list_find_index(global.saveroom, id) != -1)
    instance_destroy()
ini_open(global.savedata_ini)
tutorial_done = ini_read_real("story", "tutorial_done", 0)
ini_close()
tutorial_tvshow = 0
vis = 1
